name: Release

on:
  workflow_run:
    workflows: [Preintegration]
    types: [completed]
    branches: [main]

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  preintegration:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: sleep 10

      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag
        run: |
          git remote set-url --push origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          TAG=$(date)
          git tag "$TAG"
          git push origin "$TAG"
